世界白名单:
  - world
  - abc
  - xsfb
版本号: 20220125
帮助:
  - '------ Mytp Manual ------'
  - 打开菜单 /mytp open
  - 添加白名单 /mytp 添加白名单 玩家昵称 (后台进行)
  - 删除白名单 /mytp 删除白名单 玩家昵称 (后台进行)
  - '------ Mytp Manual ------'
是否使用快捷工具: true
快捷工具ID: 347
是否启用打开音效: true
最多同时存在家: 5
传送邀请花费: 10.0
设置家花费: 10.0
设置重生点花费: 1000.0
开启设置重生点: false
返回死亡点花费: 1000.0
随机传送花费: 0.0
强制回主城: false
是否进服回城: false
主城坐标: "null"
wild_maxX: 100
wild_minX: 10
wild_maxZ: 100
wild_minZ: 10
#限制
禁止随机传送世界:
  - world
禁止玩家传送世界:
  - 233
禁止返回死亡点世界:
  - 233
设置家世界:
  - world